subscription_short_name     = "premium"
platform_env                = "prod"
app_env                     = "live"
default_location            = "uksouth"
container_registry          = "codebuilddeploy.azurecr.io"
container_registry_username = "codebuilddeploy"